insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (1, 'Refridgerator', 3.5, 466.85);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (2, 'Microwave', 1, 641.02);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (3, 'Television', 3.5, 878.57);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (4, 'Oven', 1.5, 914.9);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (5, 'Air Conditioner', 3.5, 966.91);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (6, 'Refridgerator', 4, 339.01);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (7, 'Dryer', 2, 746.89);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (8, 'Dryer', 2.5, 606.25);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (9, 'Microwave', 1.5, 882.52);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (10, 'Dishwasher', 2, 150.8);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (11, 'Dryer', 4.5, 330.92);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (12, 'Air Conditioner', 1.5, 676.58);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (13, 'Dryer', 4, 706.23);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (14, 'Refridgerator', 3, 911.51);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (15, 'Air Conditioner', 4.5, 363.24);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (16, 'Microwave', 4, 353.62);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (17, 'Refridgerator', 2, 730.67);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (18, 'Dishwasher', 1.5, 628.48);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (19, 'Dryer', 4, 907.06);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (20, 'Oven', 3, 495.79);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (21, 'Television', 2, 794.29);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (22, 'Refridgerator', 1.5, 561.3);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (23, 'Refridgerator', 4, 332.22);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (24, 'Dryer', 3, 964.9);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (25, 'Dishwasher', 3.5, 982.28);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (26, 'Television', 2.5, 280.13);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (27, 'Air Conditioner', 3, 884.73);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (28, 'Air Conditioner', 1, 374.83);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (29, 'Dryer', 2.5, 815.83);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (30, 'Central Heating', 3.5, 662.34);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (31, 'Central Heating', 1, 255.14);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (32, 'Dishwasher', 5, 160.28);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (33, 'Refridgerator', 3, 643.08);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (34, 'Dishwasher', 3, 969.13);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (35, 'Dishwasher', 2.5, 665.23);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (36, 'Refridgerator', 4, 800.58);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (37, 'Central Heating', 4.5, 688.65);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (38, 'Refridgerator', 2, 520.05);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (39, 'Refridgerator', 1, 684.81);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (40, 'Television', 1, 997.55);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (41, 'Dryer', 5, 620.38);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (42, 'Dryer', 5, 225.69);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (43, 'Microwave', 4, 537.75);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (44, 'Microwave', 4, 993.66);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (45, 'Dishwasher', 3.5, 172.69);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (46, 'Dishwasher', 3, 975.54);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (47, 'Air Conditioner', 4.5, 332.07);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (48, 'Television', 4.5, 838.98);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (49, 'Dryer', 3.5, 388.44);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (50, 'Microwave', 4, 814.35);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (51, 'Central Heating', 3, 764.0);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (52, 'Oven', 4, 373.42);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (53, 'Central Heating', 4, 715.72);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (54, 'Oven', 4, 240.37);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (55, 'Refridgerator', 1, 535.0);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (56, 'Microwave', 2.5, 206.65);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (57, 'Refridgerator', 5, 754.22);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (58, 'Microwave', 2, 432.37);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (59, 'Refridgerator', 1.5, 414.62);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (60, 'Television', 4.5, 916.19);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (61, 'Microwave', 5, 715.86);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (62, 'Dishwasher', 3, 468.62);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (63, 'Dishwasher', 3, 397.93);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (64, 'Refridgerator', 5, 767.28);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (65, 'Dishwasher', 3, 432.04);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (66, 'Dishwasher', 4.5, 563.45);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (67, 'Dishwasher', 1, 497.89);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (68, 'Oven', 2.5, 544.05);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (69, 'Dryer', 3.5, 406.17);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (70, 'Air Conditioner', 2.5, 973.5);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (71, 'Dishwasher', 1, 319.14);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (72, 'Refridgerator', 2.5, 171.13);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (73, 'Air Conditioner', 1, 306.49);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (74, 'Dryer', 1.5, 864.21);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (75, 'Television', 3.5, 698.82);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (76, 'Air Conditioner', 1.5, 398.78);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (77, 'Television', 2.5, 332.3);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (78, 'Oven', 4, 588.42);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (79, 'Refridgerator', 2.5, 656.86);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (80, 'Dryer', 3.5, 233.31);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (81, 'Oven', 1, 472.86);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (82, 'Air Conditioner', 2.5, 471.58);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (83, 'Dryer', 3.5, 667.87);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (84, 'Television', 3, 263.99);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (85, 'Microwave', 4, 261.3);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (86, 'Television', 1.5, 758.6);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (87, 'Microwave', 2.5, 857.05);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (88, 'Central Heating', 2.5, 388.91);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (89, 'Oven', 4.5, 851.29);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (90, 'Dishwasher', 2, 767.44);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (91, 'Central Heating', 4, 464.26);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (92, 'Oven', 3.5, 445.27);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (93, 'Air Conditioner', 2.5, 407.96);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (94, 'Microwave', 3, 240.76);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (95, 'Microwave', 4, 431.68);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (96, 'Microwave', 3, 993.4);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (97, 'Oven', 4, 303.05);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (98, 'Dryer', 1.5, 651.29);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (99, 'Air Conditioner', 2.5, 765.32);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (100, 'Television', 2, 745.89);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (101, 'Central Heating', 4.5, 157.35);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (102, 'Oven', 3.5, 424.33);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (103, 'Oven', 4.5, 868.38);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (104, 'Dryer', 3, 682.14);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (105, 'Dryer', 4.5, 245.01);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (106, 'Central Heating', 2, 916.56);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (107, 'Central Heating', 5, 480.94);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (108, 'Air Conditioner', 1.5, 349.37);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (109, 'Refridgerator', 3.5, 496.92);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (110, 'Dishwasher', 3.5, 722.47);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (111, 'Dryer', 2, 397.82);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (112, 'Air Conditioner', 2, 915.4);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (113, 'Refridgerator', 2.5, 768.85);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (114, 'Microwave', 4.5, 894.71);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (115, 'Central Heating', 2, 600.41);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (116, 'Dryer', 4.5, 591.34);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (117, 'Television', 4.5, 595.21);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (118, 'Dishwasher', 5, 655.18);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (119, 'Central Heating', 1, 899.25);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (120, 'Air Conditioner', 1.5, 610.04);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (121, 'Air Conditioner', 4, 521.14);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (122, 'Microwave', 3, 560.28);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (123, 'Refridgerator', 3.5, 196.4);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (124, 'Air Conditioner', 2, 526.12);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (125, 'Refridgerator', 4, 245.84);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (126, 'Television', 1.5, 270.65);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (127, 'Dryer', 2.5, 600.33);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (128, 'Television', 3, 952.05);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (129, 'Dishwasher', 1, 889.87);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (130, 'Refridgerator', 3.5, 474.1);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (131, 'Refridgerator', 3, 779.73);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (132, 'Dryer', 3, 875.99);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (133, 'Refridgerator', 1.5, 244.88);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (134, 'Air Conditioner', 3.5, 499.6);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (135, 'Oven', 3, 777.18);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (136, 'Dryer', 3, 544.8);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (137, 'Dishwasher', 1, 435.1);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (138, 'Microwave', 3, 276.67);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (139, 'Dryer', 4.5, 666.7);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (140, 'Oven', 4.5, 687.72);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (141, 'Oven', 1.5, 993.88);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (142, 'Oven', 3.5, 899.47);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (143, 'Air Conditioner', 1.5, 163.63);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (144, 'Dryer', 1.5, 295.04);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (145, 'Dishwasher', 1, 829.42);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (146, 'Refridgerator', 3, 637.19);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (147, 'Television', 2, 701.66);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (148, 'Dryer', 4.5, 199.7);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (149, 'Central Heating', 3, 969.31);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (150, 'Refridgerator', 2, 345.28);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (151, 'Oven', 4, 539.3);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (152, 'Air Conditioner', 1.5, 283.37);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (153, 'Central Heating', 3.5, 275.14);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (154, 'Microwave', 2.5, 415.03);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (155, 'Dishwasher', 4, 922.4);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (156, 'Oven', 2.5, 173.46);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (157, 'Dishwasher', 4.5, 497.56);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (158, 'Refridgerator', 2.5, 234.77);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (159, 'Dishwasher', 2.5, 971.73);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (160, 'Oven', 1.5, 152.86);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (161, 'Central Heating', 4.5, 210.94);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (162, 'Television', 3.5, 186.97);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (163, 'Dryer', 2, 657.76);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (164, 'Dryer', 2.5, 753.4);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (165, 'Oven', 3.5, 691.99);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (166, 'Oven', 5, 322.42);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (167, 'Dryer', 3, 405.85);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (168, 'Microwave', 4, 922.35);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (169, 'Microwave', 3, 578.38);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (170, 'Dishwasher', 4, 857.59);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (171, 'Central Heating', 3.5, 729.18);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (172, 'Microwave', 4.5, 646.37);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (173, 'Dishwasher', 2, 534.35);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (174, 'Dryer', 3, 907.68);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (175, 'Air Conditioner', 1.5, 833.85);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (176, 'Television', 3.5, 562.5);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (177, 'Television', 3, 666.54);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (178, 'Dishwasher', 1, 992.84);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (179, 'Dryer', 3.5, 451.58);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (180, 'Microwave', 4, 562.07);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (181, 'Television', 4, 486.91);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (182, 'Dryer', 2, 180.06);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (183, 'Television', 4, 788.82);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (184, 'Central Heating', 3.5, 690.85);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (185, 'Dishwasher', 3, 436.84);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (186, 'Air Conditioner', 2, 232.12);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (187, 'Dryer', 2, 338.39);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (188, 'Dishwasher', 3.5, 235.89);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (189, 'Refridgerator', 4, 678.42);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (190, 'Refridgerator', 3, 306.11);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (191, 'Dryer', 4.5, 881.98);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (192, 'Central Heating', 2, 288.2);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (193, 'Dryer', 3, 825.2);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (194, 'Dishwasher', 3.5, 613.21);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (195, 'Dishwasher', 4.5, 188.29);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (196, 'Central Heating', 2, 884.58);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (197, 'Central Heating', 1, 993.11);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (198, 'Air Conditioner', 4.5, 326.48);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (199, 'Oven', 3.5, 575.05);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (200, 'Air Conditioner', 1.5, 797.84);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (201, 'Central Heating', 2, 364.59);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (202, 'Television', 4, 827.48);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (203, 'Television', 4.5, 206.73);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (204, 'Microwave', 3.5, 605.07);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (205, 'Dryer', 1.5, 380.15);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (206, 'Central Heating', 5, 618.27);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (207, 'Dryer', 1, 237.9);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (208, 'Air Conditioner', 2.5, 216.73);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (209, 'Dishwasher', 2, 560.28);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (210, 'Oven', 4.5, 834.45);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (211, 'Microwave', 4, 191.28);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (212, 'Television', 1.5, 423.6);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (213, 'Television', 2, 500.28);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (214, 'Air Conditioner', 2.5, 215.45);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (215, 'Central Heating', 3.5, 859.78);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (216, 'Air Conditioner', 2, 602.96);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (217, 'Television', 4.5, 417.5);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (218, 'Dryer', 1.5, 602.24);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (219, 'Central Heating', 3, 728.72);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (220, 'Oven', 1.5, 874.43);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (221, 'Air Conditioner', 1.5, 680.38);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (222, 'Air Conditioner', 3, 887.18);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (223, 'Oven', 3.5, 760.22);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (224, 'Dryer', 2, 405.1);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (225, 'Microwave', 1.5, 582.98);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (226, 'Refridgerator', 5, 553.76);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (227, 'Dryer', 3, 518.3);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (228, 'Microwave', 4, 711.25);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (229, 'Dryer', 1, 782.64);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (230, 'Microwave', 4, 627.13);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (231, 'Oven', 2, 412.7);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (232, 'Dryer', 5, 714.81);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (233, 'Oven', 2, 765.21);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (234, 'Dryer', 1.5, 914.0);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (235, 'Television', 3.5, 438.34);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (236, 'Oven', 4, 418.48);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (237, 'Dryer', 3.5, 727.56);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (238, 'Dryer', 2, 548.8);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (239, 'Dishwasher', 2.5, 468.7);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (240, 'Dishwasher', 2.5, 164.39);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (241, 'Dishwasher', 4.5, 460.13);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (242, 'Refridgerator', 4, 465.02);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (243, 'Central Heating', 2, 886.47);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (244, 'Oven', 4, 159.15);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (245, 'Dishwasher', 3, 922.76);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (246, 'Microwave', 2, 670.58);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (247, 'Television', 3.5, 155.74);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (248, 'Dishwasher', 4.5, 973.49);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (249, 'Refridgerator', 3.5, 528.26);
insert into HomeAppliances (ID, ApplianceName, ApplianceRating, ApplianceConsumption) values (250, 'Dishwasher', 3.5, 781.74);
