insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (1, 37, '59 Mosinee Hill', 'PO Box 94307', 'Boise', 'Idaho', '78384', 14);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (2, 210, '4696 Graceland Point', 'PO Box 14567', 'Salt Lake City', 'Utah', '5564', 9);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (3, 241, '2345 American Ash Place', 'Apt 1611', 'Oceanside', 'California', '507', 18);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (4, 136, '88045 Hintze Trail', 'Room 1465', 'Bethesda', 'Maryland', '38', 11);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (5, 91, '707 Drewry Avenue', 'Suite 99', 'New York City', 'New York', '9246', 10);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (6, 3, '677 Sachtjen Drive', 'Apt 1343', 'Rochester', 'New York', '1', 10);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (7, 102, '57 Lotheville Circle', 'Suite 77', 'Lexington', 'Kentucky', '75344', 14);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (8, 124, '8 Garrison Point', 'Apt 1402', 'Pensacola', 'Florida', '26', 14);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (9, 139, '64947 Cody Pass', 'Apt 372', 'Houston', 'Texas', '980', 11);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (10, 113, '3668 Everett Plaza', 'Suite 3', 'El Paso', 'Texas', '46239', 18);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (11, 8, '000 Cardinal Avenue', 'PO Box 12354', 'Youngstown', 'Ohio', '2375', 11);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (12, 155, '5 Springs Way', '15th Floor', 'Phoenix', 'Arizona', '2358', 20);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (13, 213, '64 Kensington Crossing', '11th Floor', 'Spartanburg', 'South Carolina', '648', 7);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (14, 216, '09 Anzinger Hill', '14th Floor', 'Bethesda', 'Maryland', '7037', 17);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (15, 236, '70386 Maryland Lane', 'Suite 82', 'Pocatello', 'Idaho', '18295', 18);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (16, 64, '5 Continental Street', 'Room 1905', 'Tucson', 'Arizona', '7894', 15);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (17, 180, '14 Mallard Street', 'Suite 24', 'Orlando', 'Florida', '75668', 9);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (18, 144, '0624 Elka Pass', 'PO Box 88204', 'Philadelphia', 'Pennsylvania', '2', 4);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (19, 92, '4885 Havey Park', 'PO Box 33759', 'Charleston', 'West Virginia', '9258', 4);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (20, 152, '6 Northwestern Plaza', 'Room 861', 'San Francisco', 'California', '52636', 17);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (21, 119, '9248 Eagan Alley', 'PO Box 6532', 'Atlanta', 'Georgia', '5082', 12);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (22, 167, '5485 Memorial Plaza', 'PO Box 96450', 'Springfield', 'Illinois', '31651', 11);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (23, 44, '062 Sullivan Alley', '4th Floor', 'San Francisco', 'California', '6948', 4);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (24, 80, '91190 Westport Drive', 'Apt 418', 'Birmingham', 'Alabama', '76587', 14);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (25, 19, '2 Utah Center', 'Room 1199', 'Orange', 'California', '77706', 17);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (26, 90, '8754 Farmco Trail', 'Room 282', 'Murfreesboro', 'Tennessee', '58', 3);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (27, 201, '7 Clemons Terrace', 'PO Box 48142', 'Waco', 'Texas', '6094', 10);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (28, 28, '3201 Mcbride Junction', 'Suite 51', 'Kansas City', 'Missouri', '187', 8);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (29, 143, '2 Manley Point', 'PO Box 71722', 'Philadelphia', 'Pennsylvania', '28255', 3);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (30, 57, '13787 Sullivan Drive', 'PO Box 43196', 'Mobile', 'Alabama', '14108', 13);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (31, 250, '2 Clove Parkway', '14th Floor', 'Mobile', 'Alabama', '255', 14);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (32, 55, '313 Orin Plaza', 'PO Box 46132', 'Dallas', 'Texas', '588', 16);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (33, 242, '0 Ridge Oak Plaza', 'Room 1325', 'Peoria', 'Illinois', '583', 6);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (34, 160, '14263 Bunker Hill Lane', 'Suite 74', 'Wichita', 'Kansas', '737', 19);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (35, 146, '8053 Morning Parkway', 'Suite 13', 'Racine', 'Wisconsin', '3', 15);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (36, 149, '710 Judy Alley', 'Room 639', 'Chicago', 'Illinois', '5524', 9);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (37, 23, '14544 Mockingbird Hill', '2nd Floor', 'Santa Ana', 'California', '207', 7);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (38, 9, '250 Chinook Point', '4th Floor', 'Raleigh', 'North Carolina', '085', 11);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (39, 50, '97 Buhler Terrace', 'Apt 606', 'Chicago', 'Illinois', '29698', 14);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (40, 77, '63 Briar Crest Circle', '2nd Floor', 'Portland', 'Oregon', '94', 12);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (41, 233, '8 Bartelt Crossing', '6th Floor', 'Louisville', 'Kentucky', '6', 4);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (42, 150, '7 Memorial Park', 'PO Box 39602', 'Fort Lauderdale', 'Florida', '286', 20);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (43, 210, '3 Mcguire Street', 'Suite 55', 'Evansville', 'Indiana', '1', 12);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (44, 144, '611 Hoard Parkway', '4th Floor', 'San Francisco', 'California', '0', 13);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (45, 145, '726 Autumn Leaf Place', 'PO Box 75242', 'Sioux Falls', 'South Dakota', '08', 18);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (46, 58, '64504 Cordelia Terrace', '19th Floor', 'Birmingham', 'Alabama', '8', 4);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (47, 157, '9653 Gale Circle', '20th Floor', 'Houston', 'Texas', '5180', 18);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (48, 105, '406 Donald Alley', 'Room 988', 'Stamford', 'Connecticut', '9831', 3);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (49, 98, '448 Golf Course Court', 'Apt 757', 'Richmond', 'Virginia', '88', 2);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (50, 87, '38126 Pond Alley', 'Room 2', 'Boise', 'Idaho', '2972', 17);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (51, 6, '4958 Harbort Avenue', 'PO Box 42857', 'Santa Ana', 'California', '921', 14);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (52, 7, '5 High Crossing Plaza', '15th Floor', 'Sioux Falls', 'South Dakota', '10829', 20);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (53, 242, '97 Dwight Alley', 'Apt 291', 'Amarillo', 'Texas', '968', 11);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (54, 228, '1718 Dahle Hill', 'PO Box 44759', 'Corpus Christi', 'Texas', '5781', 3);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (55, 137, '8289 6th Circle', 'Room 820', 'Orlando', 'Florida', '701', 17);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (56, 79, '32420 Northfield Court', 'Apt 308', 'Suffolk', 'Virginia', '81591', 13);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (57, 65, '15417 American Ash Hill', 'Room 1930', 'Tampa', 'Florida', '16373', 21);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (58, 208, '967 Arapahoe Plaza', 'Suite 61', 'North Little Rock', 'Arkansas', '5141', 17);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (59, 230, '82708 Clarendon Pass', 'Room 1195', 'Des Moines', 'Iowa', '93', 1);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (60, 112, '5095 Prairieview Crossing', 'PO Box 66896', 'Milwaukee', 'Wisconsin', '0379', 8);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (61, 5, '8 Steensland Place', 'Apt 1695', 'Washington', 'District of Columbia', '2665', 20);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (62, 38, '04662 Green Ridge Terrace', '8th Floor', 'Miami', 'Florida', '686', 16);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (63, 200, '799 Londonderry Trail', 'Suite 39', 'New Orleans', 'Louisiana', '17', 18);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (64, 145, '2 Cascade Pass', 'Room 1164', 'Henderson', 'Nevada', '1726', 14);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (65, 112, '63408 Clove Parkway', 'Room 1577', 'Brooklyn', 'New York', '0', 17);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (66, 36, '428 Loftsgordon Place', 'Room 1482', 'Richmond', 'Virginia', '02619', 9);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (67, 37, '99 Talisman Circle', 'Suite 45', 'Brooklyn', 'New York', '19835', 16);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (68, 54, '3730 Thierer Hill', '1st Floor', 'Buffalo', 'New York', '5', 17);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (69, 221, '8 Pepper Wood Circle', 'Apt 1408', 'Kansas City', 'Missouri', '4', 15);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (70, 168, '943 Roxbury Terrace', 'PO Box 29511', 'Fort Lauderdale', 'Florida', '05', 10);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (71, 62, '8 Rutledge Junction', 'Apt 911', 'Houston', 'Texas', '7', 16);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (72, 134, '32 Dwight Drive', '6th Floor', 'Cincinnati', 'Ohio', '2527', 10);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (73, 63, '77 Donald Hill', '18th Floor', 'El Paso', 'Texas', '9', 11);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (74, 153, '435 Waubesa Parkway', 'Apt 33', 'Springfield', 'Illinois', '6421', 14);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (75, 195, '4294 Towne Place', 'Suite 41', 'Kansas City', 'Missouri', '961', 19);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (76, 154, '1993 Sundown Court', 'Room 365', 'Olympia', 'Washington', '634', 6);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (77, 176, '9 Kings Drive', 'PO Box 21048', 'Norfolk', 'Virginia', '3429', 10);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (78, 184, '796 Farmco Drive', 'Suite 30', 'Miami', 'Florida', '3454', 16);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (79, 65, '14188 Division Drive', 'Suite 57', 'Pittsburgh', 'Pennsylvania', '1153', 15);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (80, 161, '236 Forest Dale Place', 'PO Box 21471', 'Cleveland', 'Ohio', '9', 8);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (81, 180, '15987 Rusk Trail', 'Apt 1637', 'Omaha', 'Nebraska', '2588', 21);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (82, 170, '69669 Stuart Center', 'Room 1524', 'Dayton', 'Ohio', '509', 11);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (83, 203, '86 Jenna Terrace', 'Room 164', 'Albuquerque', 'New Mexico', '19365', 21);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (84, 203, '26677 Spaight Alley', 'Room 623', 'Baton Rouge', 'Louisiana', '6012', 17);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (85, 235, '63032 Kipling Way', 'Apt 22', 'Omaha', 'Nebraska', '68', 10);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (86, 171, '79 Little Fleur Place', 'Suite 13', 'Reston', 'Virginia', '22', 8);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (87, 53, '4 Bartillon Trail', 'Suite 41', 'Brockton', 'Massachusetts', '92', 9);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (88, 160, '6 Forest Run Terrace', 'Room 980', 'Concord', 'California', '03936', 9);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (89, 22, '4 Sunfield Terrace', 'Apt 1821', 'New Brunswick', 'New Jersey', '46919', 15);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (90, 218, '59901 Merchant Alley', '14th Floor', 'Dayton', 'Ohio', '3', 15);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (91, 57, '7 Parkside Avenue', 'PO Box 34671', 'Indianapolis', 'Indiana', '8', 15);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (92, 15, '58391 Jackson Way', 'Room 1838', 'Washington', 'District of Columbia', '2', 2);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (93, 117, '6 Lighthouse Bay Way', 'Suite 58', 'Pasadena', 'California', '8', 15);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (94, 14, '52 Trailsway Lane', 'PO Box 48543', 'Long Beach', 'California', '9', 5);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (95, 94, '420 American Ash Park', '12th Floor', 'Topeka', 'Kansas', '85', 2);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (96, 226, '111 Troy Trail', 'Apt 1480', 'Boise', 'Idaho', '0', 17);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (97, 100, '5 Tennessee Park', 'Suite 16', 'Columbus', 'Ohio', '14708', 3);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (98, 182, '15 Banding Parkway', 'PO Box 80104', 'Minneapolis', 'Minnesota', '2573', 5);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (99, 223, '130 Stoughton Hill', 'PO Box 52643', 'Fairfield', 'Connecticut', '3181', 5);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (100, 239, '761 Menomonie Pass', '11th Floor', 'Alpharetta', 'Georgia', '2', 15);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (101, 55, '8 Autumn Leaf Parkway', 'Apt 1154', 'El Paso', 'Texas', '0', 10);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (102, 238, '2174 Bowman Junction', 'PO Box 14632', 'Denver', 'Colorado', '0', 18);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (103, 216, '02393 Transport Pass', 'Apt 567', 'Boston', 'Massachusetts', '66324', 19);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (104, 159, '6136 Lunder Point', 'Room 1751', 'Davenport', 'Iowa', '416', 8);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (105, 130, '259 Commercial Terrace', 'Suite 72', 'Washington', 'District of Columbia', '6', 10);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (106, 17, '4 Manufacturers Avenue', '20th Floor', 'Richmond', 'Virginia', '4399', 3);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (107, 33, '2 Hudson Junction', '20th Floor', 'Saint Paul', 'Minnesota', '5', 11);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (108, 50, '2531 Hudson Drive', 'PO Box 38530', 'Shreveport', 'Louisiana', '180', 20);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (109, 202, '7734 Dryden Plaza', 'Room 443', 'Odessa', 'Texas', '731', 18);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (110, 133, '3 Brentwood Alley', 'Suite 18', 'Seattle', 'Washington', '6946', 1);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (111, 192, '777 Morningstar Place', 'Suite 41', 'Seattle', 'Washington', '6', 2);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (112, 203, '7 Katie Road', '11th Floor', 'Durham', 'North Carolina', '1496', 10);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (113, 70, '439 Moose Trail', 'Room 668', 'Port Washington', 'New York', '4646', 11);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (114, 75, '3304 Coleman Park', 'Room 12', 'San Antonio', 'Texas', '7', 17);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (115, 212, '9698 Huxley Junction', 'Room 1014', 'Memphis', 'Tennessee', '5', 8);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (116, 27, '67473 Mifflin Lane', 'Apt 237', 'Lincoln', 'Nebraska', '56', 20);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (117, 30, '4 Blackbird Circle', 'Suite 32', 'Waterbury', 'Connecticut', '0337', 13);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (118, 162, '343 Dorton Road', 'Suite 81', 'Greenville', 'South Carolina', '44', 1);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (119, 215, '0 Hayes Avenue', 'Room 1347', 'Birmingham', 'Alabama', '6415', 6);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (120, 32, '12 Hazelcrest Center', 'PO Box 72138', 'Pasadena', 'Texas', '4', 9);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (121, 6, '0 Sloan Plaza', '5th Floor', 'Gainesville', 'Georgia', '91902', 5);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (122, 187, '09 Jenifer Parkway', 'Room 523', 'Harrisburg', 'Pennsylvania', '15', 7);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (123, 91, '447 Fulton Drive', 'Apt 1485', 'Bradenton', 'Florida', '3', 18);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (124, 107, '87 Springview Hill', 'Suite 52', 'Durham', 'North Carolina', '411', 20);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (125, 160, '84 8th Pass', 'Suite 68', 'Jackson', 'Mississippi', '29', 18);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (126, 142, '45672 Center Place', 'Suite 40', 'Indianapolis', 'Indiana', '0', 13);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (127, 16, '91283 Moose Plaza', 'Room 1265', 'Greensboro', 'North Carolina', '489', 7);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (128, 99, '63 Hallows Parkway', '18th Floor', 'New York City', 'New York', '695', 21);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (129, 100, '4669 Waxwing Plaza', 'Suite 69', 'Birmingham', 'Alabama', '087', 10);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (130, 198, '90 Clemons Place', 'PO Box 50497', 'Longview', 'Texas', '9', 11);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (131, 97, '451 Corben Avenue', 'Room 1724', 'Boston', 'Massachusetts', '2324', 15);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (132, 42, '68 Mccormick Hill', '16th Floor', 'Asheville', 'North Carolina', '35198', 2);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (133, 215, '979 Rockefeller Trail', 'Room 1084', 'Erie', 'Pennsylvania', '384', 17);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (134, 55, '8030 Moulton Hill', 'Apt 1103', 'Miami', 'Florida', '39546', 2);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (135, 199, '51 Springview Pass', 'Apt 1320', 'Melbourne', 'Florida', '2', 13);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (136, 110, '72 Vera Place', '11th Floor', 'London', 'Kentucky', '733', 19);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (137, 184, '15 Cody Park', '10th Floor', 'Palo Alto', 'California', '0', 18);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (138, 40, '5 Manley Way', 'Room 1344', 'Tacoma', 'Washington', '57', 3);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (139, 41, '54 Barnett Plaza', '11th Floor', 'San Antonio', 'Texas', '2143', 6);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (140, 53, '4877 Granby Center', 'PO Box 45697', 'West Palm Beach', 'Florida', '7928', 2);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (141, 193, '09 Veith Center', 'Suite 57', 'Seattle', 'Washington', '030', 6);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (142, 221, '5 Pond Plaza', 'Room 1335', 'Phoenix', 'Arizona', '6', 12);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (143, 165, '35168 Onsgard Road', 'Apt 1719', 'Atlanta', 'Georgia', '38654', 8);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (144, 70, '10038 Washington Junction', 'Room 707', 'Amarillo', 'Texas', '32254', 6);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (145, 128, '595 Dovetail Pass', '12th Floor', 'Portland', 'Oregon', '244', 10);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (146, 88, '583 Di Loreto Terrace', 'PO Box 63062', 'Waltham', 'Massachusetts', '30', 1);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (147, 76, '8508 Canary Plaza', '14th Floor', 'Stockton', 'California', '06431', 15);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (148, 11, '3036 Scott Trail', 'PO Box 56679', 'Birmingham', 'Alabama', '9', 5);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (149, 181, '652 Springview Hill', 'Apt 753', 'El Paso', 'Texas', '453', 11);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (150, 6, '7906 Mariners Cove Way', 'PO Box 57722', 'Amarillo', 'Texas', '3626', 14);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (151, 18, '63 Hollow Ridge Alley', 'Apt 1102', 'Manassas', 'Virginia', '695', 15);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (152, 24, '2 Upham Avenue', 'Room 1836', 'Minneapolis', 'Minnesota', '27', 8);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (153, 96, '3 Del Sol Circle', 'Suite 87', 'Salt Lake City', 'Utah', '89', 10);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (154, 132, '17 Montana Hill', '13th Floor', 'Washington', 'District of Columbia', '448', 8);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (155, 40, '8 Village Green Circle', '3rd Floor', 'Vero Beach', 'Florida', '347', 4);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (156, 26, '1 Walton Crossing', '19th Floor', 'Flint', 'Michigan', '0', 8);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (157, 123, '4 Northfield Road', '13th Floor', 'San Antonio', 'Texas', '6', 15);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (158, 32, '06551 Armistice Court', 'Apt 1844', 'San Francisco', 'California', '077', 5);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (159, 91, '980 Arizona Point', 'PO Box 64586', 'Gainesville', 'Georgia', '641', 6);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (160, 141, '00745 Old Shore Center', '19th Floor', 'Chula Vista', 'California', '75568', 14);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (161, 42, '60 Lake View Alley', 'PO Box 58044', 'Lake Charles', 'Louisiana', '466', 13);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (162, 116, '09 Pierstorff Plaza', 'Room 1934', 'Escondido', 'California', '35', 18);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (163, 153, '511 Northland Way', 'Suite 67', 'Chicago', 'Illinois', '0794', 18);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (164, 156, '9 Elka Plaza', 'Suite 28', 'Battle Creek', 'Michigan', '23', 5);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (165, 103, '8412 Scott Road', 'Apt 327', 'Missoula', 'Montana', '96', 16);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (166, 177, '49148 Maryland Pass', 'Apt 1370', 'Reading', 'Pennsylvania', '0', 4);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (167, 135, '16 Jackson Drive', 'Apt 1380', 'Paterson', 'New Jersey', '4', 19);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (168, 78, '0070 Sutteridge Hill', 'Apt 1519', 'Amarillo', 'Texas', '5', 5);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (169, 24, '17117 Red Cloud Crossing', 'Apt 1749', 'Grand Rapids', 'Michigan', '6', 15);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (170, 188, '4191 Packers Road', '14th Floor', 'Detroit', 'Michigan', '9', 18);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (171, 22, '743 Laurel Street', 'PO Box 42545', 'Houston', 'Texas', '64534', 9);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (172, 195, '23737 Veith Way', '6th Floor', 'Memphis', 'Tennessee', '50013', 20);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (173, 164, '18961 Di Loreto Way', 'PO Box 90444', 'El Paso', 'Texas', '1', 19);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (174, 56, '89 Eggendart Parkway', 'Suite 70', 'El Paso', 'Texas', '8777', 17);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (175, 63, '58 Porter Avenue', 'Apt 479', 'Las Vegas', 'Nevada', '830', 10);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (176, 143, '48 Ilene Alley', 'Room 123', 'Anaheim', 'California', '7', 5);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (177, 183, '6 Texas Way', 'Apt 1404', 'New Orleans', 'Louisiana', '75276', 11);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (178, 114, '49 Summit Park', 'Apt 572', 'Montgomery', 'Alabama', '4', 9);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (179, 31, '4 Darwin Street', 'PO Box 21974', 'Kansas City', 'Missouri', '144', 12);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (180, 105, '5336 Westend Trail', 'Apt 526', 'Denver', 'Colorado', '8', 16);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (181, 123, '3490 Sugar Parkway', '19th Floor', 'San Diego', 'California', '7', 9);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (182, 112, '68600 Loomis Circle', 'Suite 71', 'Boise', 'Idaho', '65', 20);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (183, 225, '15 Coolidge Junction', 'Room 110', 'Schaumburg', 'Illinois', '96922', 20);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (184, 249, '3 Westerfield Park', '7th Floor', 'Louisville', 'Kentucky', '7', 12);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (185, 224, '6395 Sherman Plaza', 'Room 684', 'Jacksonville', 'Florida', '6', 4);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (186, 74, '1 Hoepker Road', 'Apt 1090', 'Pittsburgh', 'Pennsylvania', '2', 14);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (187, 148, '2527 Nobel Street', 'PO Box 46768', 'Aurora', 'Colorado', '3232', 10);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (188, 180, '5922 Arizona Park', 'Room 576', 'Annapolis', 'Maryland', '3487', 6);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (189, 193, '83 Clemons Road', 'Apt 972', 'Montgomery', 'Alabama', '79070', 7);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (190, 31, '687 Darwin Circle', 'Apt 1789', 'Houston', 'Texas', '11934', 12);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (191, 111, '32732 Glacier Hill Road', 'PO Box 51163', 'Philadelphia', 'Pennsylvania', '7444', 16);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (192, 177, '934 Tennessee Alley', 'Suite 99', 'Gainesville', 'Florida', '8744', 15);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (193, 40, '8554 Namekagon Place', 'Apt 1669', 'Tampa', 'Florida', '17', 21);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (194, 195, '3595 Vermont Parkway', 'PO Box 62120', 'Lancaster', 'Pennsylvania', '8', 5);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (195, 24, '17020 Grayhawk Terrace', '3rd Floor', 'Stamford', 'Connecticut', '117', 8);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (196, 149, '58022 Sheridan Point', 'Apt 775', 'Chicago', 'Illinois', '191', 20);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (197, 10, '725 Nova Court', '5th Floor', 'Migrate', 'Kentucky', '098', 9);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (198, 113, '2 Fieldstone Lane', 'Suite 54', 'San Jose', 'California', '5', 9);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (199, 7, '6 Upham Point', 'PO Box 13442', 'Durham', 'North Carolina', '623', 16);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (200, 222, '74825 Steensland Street', '7th Floor', 'Mobile', 'Alabama', '10', 21);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (201, 204, '489 Badeau Plaza', 'Room 410', 'Las Vegas', 'Nevada', '08', 20);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (202, 30, '440 Alpine Trail', 'Room 1438', 'Chicago', 'Illinois', '990', 13);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (203, 118, '67353 Gale Street', 'Room 317', 'Amarillo', 'Texas', '55', 3);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (204, 89, '21 Alpine Plaza', 'Apt 234', 'Charleston', 'West Virginia', '19278', 16);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (205, 168, '50742 Northwestern Alley', 'Suite 21', 'Tucson', 'Arizona', '67', 7);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (206, 230, '1 Colorado Court', 'Room 961', 'Jamaica', 'New York', '00384', 13);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (207, 204, '5079 Fulton Lane', 'Suite 72', 'Dayton', 'Ohio', '867', 11);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (208, 222, '15394 Shoshone Plaza', 'Apt 1218', 'Seattle', 'Washington', '1907', 10);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (209, 79, '692 Washington Circle', 'Suite 62', 'Chandler', 'Arizona', '6357', 8);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (210, 160, '66 Fordem Alley', 'Suite 98', 'Pasadena', 'California', '89622', 13);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (211, 171, '21413 Carioca Lane', 'PO Box 32258', 'Bloomington', 'Illinois', '9266', 12);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (212, 152, '8 Westend Plaza', 'Apt 1627', 'Bakersfield', 'California', '4', 3);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (213, 73, '3870 Thackeray Alley', '18th Floor', 'San Bernardino', 'California', '9975', 7);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (214, 2, '8292 Muir Place', 'Apt 449', 'Charlotte', 'North Carolina', '0', 7);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (215, 1, '66410 Cambridge Court', '1st Floor', 'Washington', 'District of Columbia', '718', 14);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (216, 167, '177 Almo Pass', 'Suite 41', 'Omaha', 'Nebraska', '302', 15);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (217, 220, '4155 Crest Line Drive', 'Suite 2', 'Amarillo', 'Texas', '97494', 16);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (218, 159, '80 Mendota Place', 'Suite 12', 'Louisville', 'Kentucky', '201', 9);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (219, 47, '914 David Trail', 'PO Box 95952', 'Rochester', 'New York', '98', 3);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (220, 199, '64456 Eliot Park', 'Suite 3', 'Saint Petersburg', 'Florida', '6', 12);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (221, 52, '9 Birchwood Center', 'Room 361', 'Las Vegas', 'Nevada', '7659', 1);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (222, 90, '4 Hansons Street', 'Room 1484', 'Saint Petersburg', 'Florida', '18', 20);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (223, 28, '384 Moose Court', '19th Floor', 'East Saint Louis', 'Illinois', '04', 19);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (224, 1, '65 Waubesa Place', 'PO Box 964', 'Baltimore', 'Maryland', '604', 7);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (225, 51, '34796 Mcguire Crossing', 'PO Box 40564', 'Las Vegas', 'Nevada', '36', 13);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (226, 158, '458 Crescent Oaks Plaza', 'Suite 36', 'Seattle', 'Washington', '0469', 8);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (227, 45, '978 Fallview Drive', 'PO Box 79424', 'Fort Lauderdale', 'Florida', '8598', 14);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (228, 226, '74967 Warrior Plaza', 'PO Box 7380', 'Maple Plain', 'Minnesota', '2936', 3);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (229, 115, '410 Cardinal Terrace', 'Suite 1', 'Albuquerque', 'New Mexico', '640', 11);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (230, 142, '42081 Arrowood Street', 'Apt 379', 'Dayton', 'Ohio', '69979', 14);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (231, 224, '2 Bluestem Hill', 'Suite 49', 'Richmond', 'Virginia', '9', 2);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (232, 60, '023 Carberry Hill', 'Room 912', 'Bronx', 'New York', '31', 9);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (233, 224, '44 Manitowish Drive', '4th Floor', 'Spartanburg', 'South Carolina', '697', 17);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (234, 83, '194 Old Shore Pass', 'Suite 73', 'Trenton', 'New Jersey', '6', 10);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (235, 236, '02214 Ryan Way', 'PO Box 93237', 'El Paso', 'Texas', '29241', 19);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (236, 207, '6 Jana Lane', 'Suite 53', 'Pittsburgh', 'Pennsylvania', '7', 9);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (237, 29, '11 Dwight Street', 'Room 461', 'Gatesville', 'Texas', '4087', 4);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (238, 138, '2116 East Crossing', 'PO Box 41283', 'Honolulu', 'Hawaii', '9', 17);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (239, 185, '4355 Pine View Alley', 'Apt 1180', 'Pompano Beach', 'Florida', '163', 18);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (240, 202, '43 Sullivan Park', '13th Floor', 'New Orleans', 'Louisiana', '791', 19);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (241, 29, '0 Tennyson Plaza', '18th Floor', 'Topeka', 'Kansas', '8656', 8);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (242, 197, '6 Bunting Crossing', 'Suite 46', 'Cumming', 'Georgia', '85569', 17);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (243, 54, '67049 Doe Crossing Parkway', 'Apt 480', 'Huntsville', 'Alabama', '77', 20);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (244, 156, '3 Clyde Gallagher Place', 'PO Box 815', 'Portland', 'Oregon', '749', 4);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (245, 49, '182 Cottonwood Center', 'Room 1159', 'New York City', 'New York', '9', 19);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (246, 249, '37 Service Court', 'Suite 8', 'Santa Fe', 'New Mexico', '0392', 9);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (247, 51, '94796 Village Trail', 'PO Box 55943', 'Kansas City', 'Missouri', '03', 14);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (248, 204, '39 Maple Wood Hill', '10th Floor', 'North Hollywood', 'California', '12', 10);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (249, 139, '38321 Sherman Lane', 'Apt 843', 'Wilkes Barre', 'Pennsylvania', '593', 15);
insert into UserAddress (ID, UserID, AddressLine1, AddressLine2, City, State, ZipCode, ApartmentNumber) values (250, 70, '3 Hermina Road', 'PO Box 65715', 'Pocatello', 'Idaho', '1', 3);
